### ISSUE TITLE
Denon support: netcat not working

### ISSUE THREAD

**Issue by akrinke** [Hwulex/hyperion-config-switch#3]
The communication with Denon AVRs using netcat doesn't work. Maybe it's because the connection has to be restarted after each request.

BTW, does hyperion-config-switch.daemon.sh send requests to the AVR? I could not find related commands in the script.

**Comment by Hwulex** [comment]
Well, nearly 2.5 years later, I started my Hyperion rig from scratch and when setting up this script again I realised a few things didn't work. Apart from the instructions being mostly horrible, the power-down effect also didn't work which is what you reported on line 67. Now fixed with [commit 1c28691](https://github.com/Hwulex/hyperion-config-switch/commit/1c2869140739cd77d3ac311c58a07d034053f44b)
