### ISSUE TITLE
Denon AVR 1912 Telnet Connection

### ISSUE THREAD

**Issue by jakeholland** [Hwulex/hyperion-config-switch#4]
Not sure if anybody is watching this, but I will give it a shot. 

I have this running on Openelec with hyperion. I am having trouble getting telnet codes to come though.

I can get codes to come in by running "telnet 10.0.1.5" with no port specified on my mac. 

I have the config files setup as I am pretty sure it should be.
I have the port as an empty string currently. I have tried 23/80/8080

I don't print any errors while it is running.

Thanks for any help. I will update if I figure it out.

**Comment by Hwulex** [comment]
Hey, Jake. I don't know if I ever tested with a blank port number, but leaving a blank port on telnet is effectively the same as setting it to the default 23. It's strange you get no result.

Have you tried changing your manual command to `telnet 10.0.1.5 23` to see if port 23 works through terminal, rather than through the script?

Errors won't print to the terminal while running. Have you checked the log file? `log="/var/log/hyperion-config-switch.log"`

**Comment by Hwulex** [comment]
Closing as over a year old and no response from user. Please re-open if issue persists and need assistance.
